FROM node:20-alpine AS dev
WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/web/package.json ./apps/web/

RUN npm ci --workspace=apps/web

COPY apps/web ./apps/web
COPY package.json ./

EXPOSE 3000

CMD ["npm", "-w", "apps/web", "run", "dev", "--", "--host", "0.0.0.0"]
