apiVersion: v1
kind: Service
metadata:
  name: neptunefriend-api
  namespace: neptune-staging
  labels:
    app: neptunefriend-api
    component: backend
    project: neptunefriend
spec:
  type: ClusterIP
  selector:
    app: neptunefriend-api
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: neptunefriend-web
  namespace: neptune-staging
  labels:
    app: neptunefriend-web
    component: frontend
    project: neptunefriend
spec:
  type: ClusterIP
  selector:
    app: neptunefriend-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
