FROM node:20-alpine AS dev
WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api/package.json ./apps/api/

RUN npm ci --workspace=apps/api

COPY apps/api ./apps/api
COPY package.json ./

EXPOSE 4000

CMD ["npm", "-w", "apps/api", "run", "dev"]
